add actions

diff --git a/actions/action.yaml b/actions/action.yaml
--- a/actions/action.yaml
+++ b/actions/action.yaml
@@ -4,17 +4,17 @@ description: Detect unsafe root CA from production files
 runs:
   using: composite
   steps:
-    - name: 🔍 Check for CA in Docker based files
-      shell: bash
-      run: |
-        echo "Searching for Docker files..."
-        exists=$(find . -type f -iname '*docker*' -exec grep -qi 'https://netfree.link/dl/unix-ca.sh' {} \; -print)
-        if [ -n "$exists" ]; then
-          echo "Root CA found in [${exists}], failing..."
-          exit 1
-        else
-          echo "No root CA detected"
-        fi
+    # - name: 🔍 Check for CA in Docker based files
+    #   shell: bash
+    #   run: |
+    #     echo "Searching for Docker files..."
+    #     exists=$(find . -type f -iname '*docker*' -exec grep -qi 'https://netfree.link/dl/unix-ca.sh' {} \; -print)
+    #     if [ -n "$exists" ]; then
+    #       echo "Root CA found in [${exists}], failing..."
+    #       exit 1
+    #     else
+    #       echo "No root CA detected"
+    #     fi
 
     - name: 🔍 Check for trusted hosts
       shell: bash
