add actions

diff --git a/actions/action.yaml b/actions/action.yaml
--- a/actions/action.yaml
+++ b/actions/action.yaml
@@ -26,3 +26,15 @@ runs:
         else
           echo "No trusted hosts detected"
         fi
+
+
+    - name: 🔍 Check for trusted ca-bundle
+      shell: bash
+      run: |
+        exists=$(find . -type f -exec grep -qi 'ca-bundle.crt' {} \;)
+        if [ "$exists" ]; then
+          echo "ca-bundle.crt found in [${exists}], failing..."
+          exit 1
+        else
+          echo "No trusted hosts detected"
+        fi    
