add ca check

diff --git a/actions/action.yaml b/actions/action.yaml
--- a/actions/action.yaml
+++ b/actions/action.yaml
@@ -27,15 +27,15 @@ runs:
           echo "No trusted hosts detected"
         fi
 
-- name: 🔍 Check for export CA variables
-  shell: bash
-  run: |
-    pattern='(?i)\b(NODE_EXTRA_CA_CERTS|REQUESTS_CA_BUNDLE|SSL_CERT_FILE)\b'
-    if grep -irlE "$pattern" . > /dev/null; then
-      echo "CA variables found in the following files:"
-      grep -irlE "$pattern" .
-      echo "Failing..."
-      exit 1
-    else
-      echo "No CA variables detected"
-    fi
+    - name: 🔍 Check for export CA variables
+      shell: bash
+      run: |
+        pattern='(?i)\b(NODE_EXTRA_CA_CERTS|REQUESTS_CA_BUNDLE|SSL_CERT_FILE)\b'
+        if grep -irlE "$pattern" . > /dev/null; then
+          echo "CA variables found in the following files:"
+          grep -irlE "$pattern" .
+          echo "Failing..."
+          exit 1
+        else
+          echo "No CA variables detected"
+        fi
